// Generated by gencpp from file object_detection/BoundingBox.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_BOUNDINGBOX_H
#define OBJECT_DETECTION_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detection
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : center_x(0.0)
    , center_y(0.0)
    , width(0.0)
    , height(0.0)
    , confidence(0.0)
    , class_id(0.0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : center_x(0.0)
    , center_y(0.0)
    , width(0.0)
    , height(0.0)
    , confidence(0.0)
    , class_id(0.0)  {
  (void)_alloc;
    }



   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _class_id_type;
  _class_id_type class_id;





  typedef boost::shared_ptr< ::object_detection::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::object_detection::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::object_detection::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::object_detection::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection::BoundingBox_<ContainerAllocator1> & lhs, const ::object_detection::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.confidence == rhs.confidence &&
    lhs.class_id == rhs.class_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection::BoundingBox_<ContainerAllocator1> & lhs, const ::object_detection::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_detection::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18ce2c7c2f15e548586297b928e28f2f";
  }

  static const char* value(const ::object_detection::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18ce2c7c2f15e548ULL;
  static const uint64_t static_value2 = 0x586297b928e28f2fULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/BoundingBox";
  }

  static const char* value(const ::object_detection::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 center_x\n"
"float32 center_y\n"
"float32 width\n"
"float32 height\n"
"float32 confidence\n"
"float32 class_id\n"
;
  }

  static const char* value(const ::object_detection::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.confidence);
      stream.next(m.class_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "class_id: ";
    Printer<float>::stream(s, indent + "  ", v.class_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_BOUNDINGBOX_H
