// Generated by gencpp from file object_detection/BoundingBoxes.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_BOUNDINGBOXES_H
#define OBJECT_DETECTION_MESSAGE_BOUNDINGBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <object_detection/BoundingBox.h>

namespace object_detection
{
template <class ContainerAllocator>
struct BoundingBoxes_
{
  typedef BoundingBoxes_<ContainerAllocator> Type;

  BoundingBoxes_()
    : BoundingBoxes()  {
    }
  BoundingBoxes_(const ContainerAllocator& _alloc)
    : BoundingBoxes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::object_detection::BoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_detection::BoundingBox_<ContainerAllocator> >::other >  _BoundingBoxes_type;
  _BoundingBoxes_type BoundingBoxes;





  typedef boost::shared_ptr< ::object_detection::BoundingBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::BoundingBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBoxes_

typedef ::object_detection::BoundingBoxes_<std::allocator<void> > BoundingBoxes;

typedef boost::shared_ptr< ::object_detection::BoundingBoxes > BoundingBoxesPtr;
typedef boost::shared_ptr< ::object_detection::BoundingBoxes const> BoundingBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::BoundingBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::BoundingBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection::BoundingBoxes_<ContainerAllocator1> & lhs, const ::object_detection::BoundingBoxes_<ContainerAllocator2> & rhs)
{
  return lhs.BoundingBoxes == rhs.BoundingBoxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection::BoundingBoxes_<ContainerAllocator1> & lhs, const ::object_detection::BoundingBoxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_detection::BoundingBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::BoundingBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::BoundingBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::BoundingBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::BoundingBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::BoundingBoxes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a68dab7e3456d8b1363c13112d36861c";
  }

  static const char* value(const ::object_detection::BoundingBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa68dab7e3456d8b1ULL;
  static const uint64_t static_value2 = 0x363c13112d36861cULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/BoundingBoxes";
  }

  static const char* value(const ::object_detection::BoundingBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BoundingBox[] BoundingBoxes\n"
"\n"
"================================================================================\n"
"MSG: object_detection/BoundingBox\n"
"float32 center_x\n"
"float32 center_y\n"
"float32 width\n"
"float32 height\n"
"float32 confidence\n"
"float32 class_id\n"
;
  }

  static const char* value(const ::object_detection::BoundingBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::BoundingBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BoundingBoxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::BoundingBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::BoundingBoxes_<ContainerAllocator>& v)
  {
    s << indent << "BoundingBoxes[]" << std::endl;
    for (size_t i = 0; i < v.BoundingBoxes.size(); ++i)
    {
      s << indent << "  BoundingBoxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_detection::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.BoundingBoxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_BOUNDINGBOXES_H
